In [142]:
import pandas as pd
import numpy as np

Q1. Pandas version
What version of Pandas did you install?

In [143]:
pd.__version__

'3.0.3'

In [144]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [145]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

Q2. Records count
How many records are in the dataset?

In [146]:
# how many rows(records) are in the data?
data.shape[0]

9704

Q3. Fuel types
How many fuel types are presented in the dataset?

In [147]:
# how many fuel types are presented in the datasets? ans=2
data["fuel_type"].unique()#.shape[0]
# data.fuel_type.nunique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [148]:
data.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

Q4. Missing values
How many columns in the dataset have missing values?

In [149]:
# how many columns in data have missing values?
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [150]:
(data.isnull().sum() != 0).sum()

np.int64(4)

Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [151]:
data.groupby("origin")["fuel_efficiency_mpg"].agg(["mean", "min", "max"])

             mean       min        max
origin
Asia    14.973830  6.886245  23.759123
Europe  14.942532  6.200971  25.967222
USA     15.040204  6.695483  24.971452

In [152]:
data[data.origin == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

Q6. Median value of horsepower
Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [154]:
median_horsepower = data["horsepower"].median()
print(f"Median horsepower: {median_horsepower}")
mode_horsepower = data["horsepower"].mode()[0]
print(f"Mode horsepower: {mode_horsepower}")

Median horsepower: 149.0
Mode horsepower: 152.0

In [ ]:
data.horsepower.isnull().sum()

np.int64(708)

In [ ]:
data["horsepower"].fillna(mode_horsepower).median() # yes! it increases

np.float64(152.0)